# syntax=docker/dockerfile:1.7

# ────────────────────────────────────────────────────────────────────
# Multi-stage build for the URL Shortener (Next.js 16 + better-sqlite3).
# Produces a minimal runtime image (~150 MB) running on Node 22 / Debian slim.
# ────────────────────────────────────────────────────────────────────

ARG NODE_VERSION=22-bookworm-slim

# ── Stage 1: deps ──────────────────────────────────────────────────
# Install all dependencies (including native build tools so better-sqlite3
# can compile if no prebuilt binary is available for our platform).
FROM node:${NODE_VERSION} AS deps
RUN apt-get update && apt-get install -y --no-install-recommends \
      python3 make g++ \
 && rm -rf /var/lib/apt/lists/*
WORKDIR /app
RUN corepack enable
COPY package.json pnpm-lock.yaml ./
# Use hoisted node-linker so Next.js standalone tracing follows real paths,
# not pnpm's symlink farm — avoids missing-file errors in the runtime image.
RUN pnpm install --frozen-lockfile --config.node-linker=hoisted

# ── Stage 2: builder ───────────────────────────────────────────────
# Copy source and produce the .next/standalone bundle.
FROM node:${NODE_VERSION} AS builder
WORKDIR /app
RUN corepack enable
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1
# NEXT_PUBLIC_BASE_URL must be present at *build time* — it's inlined into
# the client bundle for short-URL generation.
ARG NEXT_PUBLIC_BASE_URL
ENV NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
RUN pnpm build

# ── Stage 3: runner ────────────────────────────────────────────────
# Minimal runtime: just Node + the standalone bundle. No pnpm, no build tools.
FROM node:${NODE_VERSION} AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# Run as a non-root user.
RUN groupadd --system --gid 1001 nodejs \
 && useradd --system --uid 1001 --gid nodejs --shell /usr/sbin/nologin nextjs

# .next/standalone already includes a trimmed node_modules with better-sqlite3
# (because of serverExternalPackages in next.config.ts).
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 3000

# server.js is generated by Next.js standalone output.
CMD ["node", "server.js"]
